### ISSUE TITLE
[Bug] Incorrect/incomplete README instructions

### ISSUE THREAD

**Issue by olivierobert** [thiri-lwin/web_scraper#8]
## Issue

While I manage to run the applications locally with `make serverdocker`, I initially tried to follow the instructions:

```
make createdb
```

Which fails with:

![image](https://user-images.githubusercontent.com/696529/225841098-20d68be1-851a-4cae-aa93-ef348f2bf212.png)

It makes sense since it requires to having a Docker container name `postgresdb` running before being able to run this command 😅 

> **Note**
> It would be best to user the attribute [container_name](https://docs.docker.com/compose/compose-file/compose-file-v3/#container_name) for containers to ensure Docker respects the name you picked:
> ![Screenshot 2566-03-17 at 14 33 41](https://user-images.githubusercontent.com/696529/225842382-81d8a2ab-c26a-4c48-a791-6f719481f1e6.png)
> Without it, Docker autogenerates the name for each service:
> ![image](https://user-images.githubusercontent.com/696529/225841992-220fb857-4a71-45c7-a34a-d6d3c5684ebd.png)

## Expected

The README instructions must contain all the required steps to set up the application.

**Comment by thiri-lwin** [comment]
Hi @olivierobert, I've made some fixes for this issue and opened PR for this. Please let me know if there is any other improvement i can do to make the instructions clear. Thank you :)
